INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ATVI', ' Activision Blizzard Inc')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ADBE', ' Adobe Systems Incorporated')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AKAM', ' Akamai Technologies Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ALXN', ' Alexion Pharmaceuticals Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ALTR', ' Altera Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AMZN', ' Amazon.com Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AMGN', ' Amgen Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ADI', ' Analog Devices Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AAPL', ' Apple Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AMAT', ' Applied Materials Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ADSK', ' Autodesk Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ADP', ' Automatic Data Processing Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('AVGO', ' Avago Technologies Limited')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('BIDU', ' Baidu Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('BBBY', ' Bed Bath &amp; Beyond Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('BIIB', ' Biogen Idec Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('BRCM', ' Broadcom Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CHRW', ' C.H. Robinson Worldwide Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CA', ' CA Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CTRX', ' Catamaran Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CELG', ' Celgene Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CERN', ' Cerner Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CHTR', ' Charter Communications Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CHKP', ' Check Point Software Technologies Ltd.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CSCO', ' Cisco Systems Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CTXS', ' Citrix Systems Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CTSH', ' Cognizant Technology Solutions Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('CMCSA', ' Comcast Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('COST', ' Costco Wholesale Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('DTV', ' DIRECTV')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('DISCA', ' Discovery Communications Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('DISH', ' DISH Network Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('DLTR', ' Dollar Tree Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('EBAY', ' eBay Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('EQIX', ' Equinix Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('EXPE', ' Expedia Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('EXPD', ' Expeditors International of Washington Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ESRX', ' Express Scripts Holding Company')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('FFIV', ' F5 Networks Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('FB', ' Facebook Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('FAST', ' Fastenal Company')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('FISV', ' Fiserv Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('GRMN', ' Garmin Ltd.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('GILD', ' Gilead Sciences Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('GOOG', ' Google Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('GOOGL', ' Google Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('HSIC', ' Henry Schein Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ILMN', ' Illumina Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('INTC', ' Intel Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('INTU', ' Intuit Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ISRG', ' Intuitive Surgical Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('GMCR', ' Keurig Green Mountain Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('KLAC', ' KLA-Tencor Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('KRFT', ' Kraft Foods Group Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('LBTYA', ' Liberty Global plc')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('LINTA', ' Liberty Interactive Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('LMCA', ' Liberty Media Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('LLTC', ' Linear Technology Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MAR', ' Marriott International')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MAT', ' Mattel Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MXIM', ' Maxim Integrated Products Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MU', ' Micron Technology Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MSFT', ' Microsoft Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MDLZ', ' Mondelez International Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MNST', ' Monster Beverage Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('MYL', ' Mylan Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('NTAP', ' NetApp Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('NFLX', ' Netflix Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('NVDA', ' NVIDIA Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('NXPI', ' NXP Semiconductors N.V.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ORLY', ' O\'Reilly Automotive Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('PCAR', ' PACCAR Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('PAYX', ' Paychex Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('QCOM', ' QUALCOMM Incorporated')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('REGN', ' Regeneron Pharmaceuticals Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('ROST', ' Ross Stores Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SNDK', ' SanDisk Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SBAC', ' SBA Communications Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('STX', ' Seagate Technology.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SIAL', ' Sigma-Aldrich Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SIRI', ' Sirius XM Holdings Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SPLS', ' Staples Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SBUX', ' Starbucks Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SRCL', ' Stericycle Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('SYMC', ' Symantec Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('TSLA', ' Tesla Motors Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('TXN', ' Texas Instruments Incorporated')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('PCLN', ' The Priceline Group Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('TSCO', ' Tractor Supply Company')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('TRIP', ' TripAdvisor Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('FOXA', ' Twenty-First Century Fox Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('VRSK', ' Verisk Analytics Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('VRTX', ' Vertex Pharmaceuticals Incorporated')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('VIAB', ' Viacom Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('VIP', ' VimpelCom Ltd.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('VOD', ' Vodafone Group Plc')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('WDC', ' Western Digital Corporation')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('WFM', ' Whole Foods Market Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('WYNN', ' Wynn Resorts Limited')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('XLNX', ' Xilinx Inc.')
INSERT INTO portfolio_stock (stock_tickr, stock_name) VALUES ('YHOO', ' Yahoo! Inc.')
